Bump to en 900b99d
Lou8is/docs.nestjs.fr pull request #189
Opened 2023-11-21 17:51 UTC by pacyL2K19

## PR Checklist
Merci de vérifier que vous suivez bien les recommandations suivantes :

- [x] Les messages de commits suivent bien les recommandations : https://github.com/nestjs/docs.nestjs.com/blob/master/CONTRIBUTING.md
- [x] L'homogénéité de la traduction est respectée (guide à venir)
- [x] Les erreurs communes sont évitées (redirection vers la version EN, traduction des ancres, ...)

## Types de PR
Quel est l'objet de cette PR :

- [ ] Traduction d'une nouvelle page
- [ ] Modification d'une page déjà traduite
- [x] màj pour suivre version EN 900b99d

## Liens 

#180 
#181 

Issue/PR/Discussion : N/A

## Autres détails (optionnel)

2023-11-21 17:51 UTC, pacyL2K19 commented
@Lou8is 
Kindly have a look

2023-11-22 09:45 UTC, Lou8is requested changes
Looking good, one small thing and we're perfect :)

2023-11-22 09:45 UTC, Lou8is commented on content/techniques/events.md
> +Le second argument (optionnel) est un objet d'options d'écoute ( [en lire plus](https://github.com/EventEmitter2/EventEmitter2#emitteronevent-listener-options-objectboolean)).
enlever le lien / ajouter ":" pour lier à l'exemple en dessous

(le lien se trouve désormais sous l'exemple)

2023-11-23 00:59 UTC, pacyL2K19 commented on content/techniques/events.md
> +Le second argument (optionnel) est un objet d'options d'écoute ( [en lire plus](https://github.com/EventEmitter2/EventEmitter2#emitteronevent-listener-options-objectboolean)).
Done

2023-11-23 07:10 UTC, Lou8is approved these changes

2023-11-23 07:11 UTC, merged

2023-11-23 07:12 UTC, Lou8is commented
Merged both PR, good job!